# Generated by Django 2.1.3 on 2018-11-08 15:42

import acads.validator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('width', models.IntegerField(default=350)),
                ('height', models.IntegerField(default=350)),
                ('document', models.FileField(blank=True, default=None, help_text='ONLY IMAGES (png,jpg)', upload_to='static/media/images', validators=[acads.validator.validate_file_extension], verbose_name='file')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(help_text="Insert Images by <img src='/static/media/imageName.jpg' class='img-responsive' style='display:inline'' width='xx' height='3yy'>")),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, to='acads.Images')),
            ],
        ),
    ]
