# Generated by Django 2.1.3 on 2018-11-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
