# Generated by Django 2.1.3 on 2018-11-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acads', '0002_auto_20181108_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Insert Images by [ImageName]'),
        ),
    ]
