# Generated by Django 2.1.3 on 2018-11-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acads', '0003_auto_20181108_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='<b>Renders Pure HTML<b> <br> Insert Images by  src="imagelink" class="img-responsive img-circle margin" style="display:inline" alt="Bird" width="{width}" height="{height}"'),
        ),
    ]
